In [ ]:
import numpy as np

1.

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a[::-1]

array([6, 5, 4, 3, 2, 1])

2.

In [ ]:
max(a[a % 2 == 1])

5

3.

In [ ]:
favnum = 17
b = np.copy(a)
b[b % 2 == 1] = favnum
b

array([17,  2, 17,  4, 17,  6])

4.

In [ ]:
n = 7
c = np.arange(n*2-1, 0, -2)
c

array([13, 11,  9,  7,  5,  3,  1])

5.

In [ ]:
n = 1.5
d = np.array([1, 2, 3, 4])
e = np.abs(d-n)
(d[np.argmin(e)], d[np.argmax(e)])

(1, 4)

6.

In [ ]:
n = 3
polynomial = np.array([4, 6, 0, 1])
# p = np.array([20, -8, 9, 4, -4])
indices = np.arange(p.size - 1, -1, -1) + 1
integrated = np.append(np.divide(p, indices), n)
integrated
# indices

array([1., 2., 0., 1., 3.])

7.

In [ ]:
xval = 1
polynomial = np.array([1, 2, 0, 1, 3])
indices = np.arange(p.size - 1, -1, -1)
derivative = np.multiply(p, indices)[:-1]
instantslope = np.sum(derivative * xval)
instantslope

11