<a href="https://colab.research.google.com/github/Quizzer515SY/mlhw/blob/main/sem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Задания для самостоятельного решения

1. Развернуть одномерный массив (сделать так, чтобы его элементы шли в обратном порядке).

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a[::-1] #reversed array

array([6, 5, 4, 3, 2, 1])

2. Найти максимальный нечетный элемент в массиве.

In [ ]:
max(a[a % 2 == 1])

5

3. Замените все нечетные элементы массива на ваше любимое число.

In [ ]:
favnum = 17
b = np.copy(a)
b[b % 2 == 1] = favnum
b

array([17,  2, 17,  4, 17,  6])

4. Создайте массив первых n нечетных чисел, записанных в порядке убывания. Например, если n=5, то ответом будет `array([9, 7, 5, 3, 1])`. Функции, которые могут пригодиться при решении: `.arange()`

In [ ]:
n = 7
c = np.arange(n*2-1, 0, -2)
c

array([13, 11,  9,  7,  5,  3,  1])

5. Вычислите самое близкое и самое дальнее числа к данному в рассматриваемом массиве чисел. Например, если на вход поступают массив `array([0, 1, 2, 3, 4])` и число 1.33, то ответом будет `(1, 4)`. Функции, которые могут пригодиться при решении: `.abs()`, `.argmax()`, `.argmin()`

In [ ]:
n = 1.5
d = np.array([1, 2, 3, 4])
e = np.abs(d-n)
(d[np.argmin(e)], d[np.argmax(e)])

(1, 4)

6. Вычисляющую первообразную заданного полинома (в качестве константы возьмите ваше любимое число). Например, если на вход поступает массив коэффициентов `array([4, 6, 0, 1])`, что соответствует полиному 4x^3 + 6x^2 + 1, на выходе получается массив коэффициентов `array([1, 2, 0, 1, -2])`, соответствующий полиному x^4 + 2x^3 + x - 2. Функции, которые могут пригодиться при решении: `.append()`

In [ ]:
n = 3
polynomial = np.array([4, 6, 0, 1])
indices = np.arange(p.size - 1, -1, -1) + 1
integrated = np.append(np.divide(p, indices), n)
integrated

array([1., 2., 0., 1., 3.])

7. Пользуясь пунктом 6, посчитайте первую производную для заданного полинома в заданной точке.

In [ ]:
xval = 1
polynomial = np.array([1, 2, 0, 1, 3])
indices = np.arange(p.size - 1, -1, -1)
derivative = np.multiply(p, indices)[:-1]
instantslope = np.sum(derivative * xval)
instantslope

11